
title: Jake P Schneider - Audio Engineer & Producer
url: 'http://JakePartridge.com'
baseurl: '' #change it according to your repository name


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
style: styles-6


#Profile information
name: Jake Schneider
tagline: Audio Engineer & Producer
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: Jk@JakePartridge.com
website: JakePartridge.com #do not add http://
facebook: 'JakePSchneider'

#Update all the sections by editing the files inside _includes folder.
